### ISSUE TITLE
Can set autoplay?

### ISSUE THREAD

**Issue by ssheduardo** [flowplayer/flowplayer-audio#3]
Hi,
With this plugin can set autoplay to audio?

**Comment by phloxic** [comment]
Yes, why not? Did you try it? `autoplay` is not an audio specific option.

**Comment by ssheduardo** [comment]
I try set autoplay:true but not play automatic.

**Comment by phloxic** [comment]
Either you have also set splash - splash and autoplay by definition contradict each other - or you are testing on a mobile device which does not allow autoplay.
This is an issue tracker, please turn to our forum https://flowplayer.org/forum/ for usage questions before you are certain that it is a bug. If you provide a link to a **minimal** sample page showing the issue, you should get an answer quickly.
